export { default as Home } from './home'
export { default as Login } from './login'
export { default as Register } from './register'
export { default as ForgotPassword } from './forgotPassword'
export { default as Search } from './search'
export { default as User } from './user'
export { default as CreateUser } from './create'
export { default as NotFoundPage } from './404'
