version: '3'
services:
  app:
    build: ./client/
    container_name: app
    volumes:
      - ./client/build:/usr/src/app/build
      - /usr/src/app/node_modules
    networks:
      - mern-app
  server:
    build: ./server/
    container_name: server
    restart: unless-stopped
    ports:
      - '5000:5000'
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mern-app
    env_file:
      - ./server/.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local